### ISSUE TITLE
@mentions could also send a private message

### ISSUE THREAD

**Issue by johncoffee** [stripedpajamas/scat#28]
Would it be an idea to have the @mention feature also send a 'normal' private message, so peoples other clients would get notified about the mentioning?

Also: Super cool project!

**Comment by stripedpajamas** [comment]
@johncoffee interesting idea. I like the idea of having a little more visibility when a PM comes in, because scat doesn't have any desktop notifications, just the yellow bar at the top. But I'm worried that sending a a 'normal' PM for every scat PM would just get way out of hand, effectively doubling bandwidth+space for these tiny chat messages. Will have to brainstorm ways to make PMs more visible.

**Comment by stripedpajamas** [comment]
Think I will close this down. scat will remain a very light client for chatting; other clients are popping up that may have broader notification support ([gester](https://github.com/stripedpajamas/gester), [misc](https://github.com/adamsky/misc), [scatter](https://github.com/evbogue/scatter)).
